### PR TITLE
#163720410 As a user and admin I can get a specific party

### PR DESCRIPTION
**Pull request by AloisBlue**
#### What does this PR do?
Gets a specific party
#### Description of Task to be completed?
As a user and admin I can get a specific party
#### How should this be manually tested?
- Clone my repo at https://github.com/AloisBlue/Politico_Backend.git
- cd Politico_Backend
- make a virtual environment i.e. python3 -m venv venv
- activate the venv i.e. source venv/bin/activate
- export FLASK_CONFIG=development
- export FLASK_APP=run.py
#### What are the relevant pivotal tracker stories?
#163720410
#### Label
Feature

#### Screenshot

screenshot from 2019-02-06 17-31-06

### CODE REVIEW

**Review by Nduhiu17 — COMMENTED** [review]
Nice...I think it's important to remove unwanted files like.  .pyc files

**Review by Nduhiu17 — COMMENTED** [review]
Nice...I think it's important to remove unwanted files like.  .pyc files

**Comment by AloisBlue** [comment]
Yeah man I am trying to resolve it with the .gitignore. Could you get me a
good way to list gitignore if possible please

**Comment by Nduhiu17** [comment]
I didn't get you right? I guess you meant a list of files to ignore. Right?

**Comment by Nduhiu17** [comment]
I didn't get you right? I guess you meant a list of files to ignore. Right?

**Comment by AloisBlue** [comment]
Yes

**Pull request merged**
